server:
  port: 8082

spring:
  application:
    name: santa
  datasource:
    Username: 'lasicode'
    Url: jdbc:postgresql://localhost:5432/santa
    password: 'password'
  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true