server:
  port: 8080

spring:
  application:
    name: newcustomer
  datasource:
    Username: 'lasicode'
    Url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    hibernate:
      ddl_auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        type: trace
  cloud:
    openfeign:
      client:
        config:
          feignName:
            loggerLevel: full
